type User {
  id: ID!
  username: String!
  email: String!
  createdAt: String!
}

type AuthError {
  message: String!
  code: String!
}

type AuthPayload {
  user: User
  token: String
  refreshToken: String
  error: AuthError
}

input SignUpInput {
  username: String!
  email: String!
  password: String!
}

input SignInInput {
  identifier: String!
  password: String!
}

type Mutation {
  signup(input: SignUpInput!): AuthPayload!
  signin(input: SignInInput!): AuthPayload!
  refreshToken(token: String!): AuthPayload!
}
